---
- name: Ensure neccesary packages for systemd user scope are installed
  become: true
  ansible.builtin.package:
    name: 
      - acl
      - systemd-container
      - libpam-systemd
    state: present
  become: true

- name: Ensure Komodo user exists
  ansible.builtin.user:
    name: "{{ komodo_user }}"
    shell: /usr/sbin/nologin
    uid: "{{ komodo_user_uid | default(omit) }}"
    groups: docker
    append: true
    create_home: true
    password: "{{ komodo_user_password | default(omit) }}"
    home: "{{ komodo_home }}"
