---
- name: Ensure mount directory exists
  ansible.builtin.file:
    path: "{{ komodo_mount_path }}"
    state: directory
    owner: "{{ komodo_user }}"
    group: "{{ komodo_user }}"
    mode: "0770"
  when:
    - komodo_mount_path is defined
    - komodo_mount_path | length > 0

- name: Mount data directory
  ansible.posix.mount:
    path: "{{ komodo_mount_path }}"
    src: "{{ komodo_mount_server }} ~ ':' ~ {{ komodo_mount_server_path }}"
    boot: true
    fstype: "{{ komodo_mount_fstype }}"
    opts: defaults
    state: mounted
  when:
    - komodo_mount_path is defined
    - komodo_mount_path | length > 0
    - komodo_mount_server is defined
    - komodo_mount_server | length > 0
    - komodo_mount_server_path is defined
    - komodo_mount_server_path | length > 0
